services:
  bw.assets:
    class: BW\AssetsBundle\Assets
    arguments: ["@kernel","@request_stack","@file_locator","@assets.packages"]
    tags:
      - { name: kernel.event_subscriber }

  twig_asset_version_extension:
    class: BW\AssetsBundle\Twig\AssetsExtension
    arguments: ["@bw.assets"]
    tags:
      - { name: twig.extension }

  bw.assets.asset_warmer:
    class: BW\AssetsBundle\CacheWarmer\AssetWarmer
    arguments: ["@twig", "@templating.finder"]
    tags:
        - { name: kernel.cache_warmer, priority: 0 }