services:
  bw.assets:
    class: BW\AssetsBundle\Assets
    arguments: ["@kernel","@request_stack","@file_locator","@assets.packages"]
    tags:
      - { name: kernel.event_subscriber }

  twig_asset_version_extension:
    class: BW\AssetsBundle\Twig\AssetsExtension
    arguments: ["@bw.assets"]
    tags:
      - { name: twig.extension }